import {
  LIST_STORED_SKILLS_ROUTE,
  GET_STORED_SKILL_ROUTE,
  CREATE_STORED_SKILL_ROUTE,
  UPDATE_STORED_SKILL_ROUTE,
  DELETE_STORED_SKILL_ROUTE,
  PUBLISH_STORED_SKILL_ROUTE,
} from '../../handlers/stored-skills';
import type { ServerRoute } from '.';

export const STORED_SKILLS_ROUTES: ServerRoute<any, any, any>[] = [
  // Stored Skills CRUD Routes
  LIST_STORED_SKILLS_ROUTE,
  GET_STORED_SKILL_ROUTE,
  CREATE_STORED_SKILL_ROUTE,
  UPDATE_STORED_SKILL_ROUTE,
  DELETE_STORED_SKILL_ROUTE,
  // Publish
  PUBLISH_STORED_SKILL_ROUTE,
];
